// Role definitions for the Training Management System
export const ROLES = {
  SYSTEM_ADMIN: 'system_admin',
  TRAINING_COORDINATOR: 'training_coordinator',
  TRAINER: 'trainer',
  TRAINEE: 'trainee',
  HOD: 'hod',
  QA_OFFICER: 'qa_officer',
  HR: 'hr',
  AUDITOR: 'auditor',
  GUEST_TRAINER: 'guest_trainer'
};

export const ROLE_LABELS = {
  [ROLES.SYSTEM_ADMIN]: 'System Administrator',
  [ROLES.TRAINING_COORDINATOR]: 'Training Coordinator',
  [ROLES.TRAINER]: 'Trainer',
  [ROLES.TRAINEE]: 'Trainee',
  [ROLES.HOD]: 'HOD / Approver / Designee',
  [ROLES.QA_OFFICER]: 'QA / Compliance Officer',
  [ROLES.HR]: 'HR / HRM',
  [ROLES.AUDITOR]: 'Auditor',
  [ROLES.GUEST_TRAINER]: 'Guest / External Trainer'
};

// Permission definitions
export const PERMISSIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  APPROVE: 'approve',
  EXPORT: 'export',
  AUDIT: 'audit',
  EXECUTE: 'execute'
};

// Module definitions
export const MODULES = {
  DASHBOARD: 'dashboard',
  USER_MANAGEMENT: 'user_management',
  SYSTEM_PERMISSIONS: 'system_permissions',
  SYSTEM_CONFIG: 'system_config',
  CATEGORIES: 'categories',
  TRAINING_TYPES: 'training_types',
  TRAINING_CREATION: 'training_creation',
  TRAINING_ASSIGNMENTS: 'training_assignments',
  ASSESSMENTS: 'assessments',
  ASSESSMENT_RESULTS: 'assessment_results',
  CERTIFICATES: 'certificates',
  ANALYTICS_REPORTS: 'analytics_reports',
  DOCUMENT_MAPPING: 'document_mapping',
  MATERIALS: 'materials',
  ROLE_MAPPING: 'role_mapping',
  JOB_RESPONSIBILITIES: 'job_responsibilities',
  MASTER_DATA: 'master_data',
  COURSE_TEMPLATES: 'course_templates',
  MATERIAL_LIBRARY: 'material_library',
  NOTIFICATIONS: 'notifications'
};

// Role-Permission Matrix
export const ROLE_PERMISSIONS = {
  [ROLES.SYSTEM_ADMIN]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.READ, PERMISSIONS.EXPORT, PERMISSIONS.AUDIT],
    [MODULES.USER_MANAGEMENT]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE, PERMISSIONS.AUDIT],
    [MODULES.SYSTEM_PERMISSIONS]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE],
    [MODULES.SYSTEM_CONFIG]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE],
    [MODULES.CATEGORIES]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE],
    [MODULES.TRAINING_TYPES]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE],
    [MODULES.TRAINING_CREATION]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE, PERMISSIONS.APPROVE],
    [MODULES.TRAINING_ASSIGNMENTS]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE, PERMISSIONS.APPROVE],
    [MODULES.ASSESSMENTS]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE, PERMISSIONS.APPROVE],
    [MODULES.ASSESSMENT_RESULTS]: [PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.EXPORT, PERMISSIONS.AUDIT],
    [MODULES.CERTIFICATES]: [PERMISSIONS.READ, PERMISSIONS.EXPORT, PERMISSIONS.AUDIT],
    [MODULES.ANALYTICS_REPORTS]: [PERMISSIONS.READ, PERMISSIONS.EXPORT, PERMISSIONS.AUDIT],
    [MODULES.DOCUMENT_MAPPING]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE],
    [MODULES.MATERIALS]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE],
    [MODULES.ROLE_MAPPING]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE],
    [MODULES.JOB_RESPONSIBILITIES]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE],
    [MODULES.MASTER_DATA]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE],
    [MODULES.COURSE_TEMPLATES]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE],
    [MODULES.MATERIAL_LIBRARY]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE, PERMISSIONS.AUDIT],
    [MODULES.NOTIFICATIONS]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.DELETE]
  },
  
  [ROLES.TRAINING_COORDINATOR]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.READ, PERMISSIONS.EXPORT],
    [MODULES.USER_MANAGEMENT]: [PERMISSIONS.READ],
    [MODULES.CATEGORIES]: [PERMISSIONS.CREATE, PERMISSIONS.READ],
    [MODULES.TRAINING_TYPES]: [PERMISSIONS.READ],
    [MODULES.TRAINING_CREATION]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.TRAINING_ASSIGNMENTS]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.APPROVE],
    [MODULES.ASSESSMENTS]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.ASSESSMENT_RESULTS]: [PERMISSIONS.READ, PERMISSIONS.EXPORT],
    [MODULES.CERTIFICATES]: [PERMISSIONS.READ, PERMISSIONS.EXPORT],
    [MODULES.ANALYTICS_REPORTS]: [PERMISSIONS.READ, PERMISSIONS.EXPORT],
    [MODULES.DOCUMENT_MAPPING]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.MATERIALS]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.COURSE_TEMPLATES]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.MATERIAL_LIBRARY]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.NOTIFICATIONS]: [PERMISSIONS.READ]
  },
  
  [ROLES.TRAINER]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.READ],
    [MODULES.TRAINING_CREATION]: [PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.TRAINING_ASSIGNMENTS]: [PERMISSIONS.READ, PERMISSIONS.EXECUTE],
    [MODULES.ASSESSMENTS]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE, PERMISSIONS.EXECUTE],
    [MODULES.ASSESSMENT_RESULTS]: [PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.CERTIFICATES]: [PERMISSIONS.READ],
    [MODULES.ANALYTICS_REPORTS]: [PERMISSIONS.READ],
    [MODULES.MATERIALS]: [PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.MATERIAL_LIBRARY]: [PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.NOTIFICATIONS]: [PERMISSIONS.READ]
  },
  
  [ROLES.TRAINEE]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.READ],
    [MODULES.TRAINING_ASSIGNMENTS]: [PERMISSIONS.READ, PERMISSIONS.EXECUTE],
    [MODULES.ASSESSMENTS]: [PERMISSIONS.READ, PERMISSIONS.EXECUTE],
    [MODULES.ASSESSMENT_RESULTS]: [PERMISSIONS.READ],
    [MODULES.CERTIFICATES]: [PERMISSIONS.READ, PERMISSIONS.EXPORT],
    [MODULES.MATERIALS]: [PERMISSIONS.READ],
    [MODULES.MATERIAL_LIBRARY]: [PERMISSIONS.READ],
    [MODULES.NOTIFICATIONS]: [PERMISSIONS.READ]
  },
  
  [ROLES.HOD]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.READ, PERMISSIONS.EXPORT],
    [MODULES.USER_MANAGEMENT]: [PERMISSIONS.READ],
    [MODULES.TRAINING_ASSIGNMENTS]: [PERMISSIONS.READ, PERMISSIONS.APPROVE],
    [MODULES.ASSESSMENT_RESULTS]: [PERMISSIONS.READ, PERMISSIONS.EXPORT],
    [MODULES.CERTIFICATES]: [PERMISSIONS.READ, PERMISSIONS.EXPORT],
    [MODULES.ANALYTICS_REPORTS]: [PERMISSIONS.READ, PERMISSIONS.EXPORT],
    [MODULES.NOTIFICATIONS]: [PERMISSIONS.READ]
  },
  
  [ROLES.QA_OFFICER]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.READ, PERMISSIONS.EXPORT, PERMISSIONS.AUDIT],
    [MODULES.TRAINING_CREATION]: [PERMISSIONS.READ, PERMISSIONS.APPROVE],
    [MODULES.TRAINING_ASSIGNMENTS]: [PERMISSIONS.READ, PERMISSIONS.AUDIT],
    [MODULES.ASSESSMENTS]: [PERMISSIONS.READ, PERMISSIONS.APPROVE, PERMISSIONS.AUDIT],
    [MODULES.ASSESSMENT_RESULTS]: [PERMISSIONS.READ, PERMISSIONS.EXPORT, PERMISSIONS.AUDIT],
    [MODULES.CERTIFICATES]: [PERMISSIONS.READ, PERMISSIONS.EXPORT, PERMISSIONS.AUDIT],
    [MODULES.ANALYTICS_REPORTS]: [PERMISSIONS.READ, PERMISSIONS.EXPORT, PERMISSIONS.AUDIT],
    [MODULES.DOCUMENT_MAPPING]: [PERMISSIONS.READ, PERMISSIONS.AUDIT],
    [MODULES.NOTIFICATIONS]: [PERMISSIONS.READ]
  },
  
  [ROLES.HR]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.READ, PERMISSIONS.EXPORT],
    [MODULES.USER_MANAGEMENT]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.ROLE_MAPPING]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.JOB_RESPONSIBILITIES]: [PERMISSIONS.CREATE, PERMISSIONS.READ, PERMISSIONS.UPDATE],
    [MODULES.ANALYTICS_REPORTS]: [PERMISSIONS.READ, PERMISSIONS.EXPORT],
    [MODULES.NOTIFICATIONS]: [PERMISSIONS.READ]
  },
  
  [ROLES.AUDITOR]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.READ, PERMISSIONS.AUDIT],
    [MODULES.USER_MANAGEMENT]: [PERMISSIONS.READ, PERMISSIONS.AUDIT],
    [MODULES.TRAINING_CREATION]: [PERMISSIONS.READ, PERMISSIONS.AUDIT],
    [MODULES.TRAINING_ASSIGNMENTS]: [PERMISSIONS.READ, PERMISSIONS.AUDIT],
    [MODULES.ASSESSMENTS]: [PERMISSIONS.READ, PERMISSIONS.AUDIT],
    [MODULES.ASSESSMENT_RESULTS]: [PERMISSIONS.READ, PERMISSIONS.AUDIT],
    [MODULES.CERTIFICATES]: [PERMISSIONS.READ, PERMISSIONS.AUDIT],
    [MODULES.ANALYTICS_REPORTS]: [PERMISSIONS.READ, PERMISSIONS.EXPORT, PERMISSIONS.AUDIT],
    [MODULES.DOCUMENT_MAPPING]: [PERMISSIONS.READ, PERMISSIONS.AUDIT],
    [MODULES.MATERIAL_LIBRARY]: [PERMISSIONS.READ, PERMISSIONS.AUDIT],
    [MODULES.NOTIFICATIONS]: [PERMISSIONS.READ]
  },
  
  [ROLES.GUEST_TRAINER]: {
    [MODULES.DASHBOARD]: [PERMISSIONS.READ],
    [MODULES.TRAINING_ASSIGNMENTS]: [PERMISSIONS.READ, PERMISSIONS.EXECUTE],
    [MODULES.ASSESSMENTS]: [PERMISSIONS.READ, PERMISSIONS.EXECUTE],
    [MODULES.ASSESSMENT_RESULTS]: [PERMISSIONS.READ],
    [MODULES.MATERIALS]: [PERMISSIONS.READ],
    [MODULES.MATERIAL_LIBRARY]: [PERMISSIONS.READ],
    [MODULES.NOTIFICATIONS]: [PERMISSIONS.READ]
  }
};

// Helper functions
export const hasPermission = (userRole, module, permission) => {
  const rolePermissions = ROLE_PERMISSIONS[userRole];
  if (!rolePermissions || !rolePermissions[module]) {
    return false;
  }
  return rolePermissions[module].includes(permission);
};

export const getUserModules = (userRole) => {
  const rolePermissions = ROLE_PERMISSIONS[userRole];
  return rolePermissions ? Object.keys(rolePermissions) : [];
};

export const canAccessModule = (userRole, module) => {
  const rolePermissions = ROLE_PERMISSIONS[userRole];
  return rolePermissions && rolePermissions[module] && rolePermissions[module].length > 0;
};